# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

t2cpp3 <- function(t, interval) {
    .Call('rhr_t2cpp3', PACKAGE = 'rhr', t, interval)
}

binnedCV <- function(xs, ys, freq, hs) {
    .Call('rhr_binnedCV', PACKAGE = 'rhr', xs, ys, freq, hs)
}

unbinnedCV <- function(xs, ys, hs) {
    .Call('rhr_unbinnedCV', PACKAGE = 'rhr', xs, ys, hs)
}

meanSquaredDistance <- function(x, y, mx, my) {
    .Call('rhr_meanSquaredDistance', PACKAGE = 'rhr', x, y, mx, my)
}

simpleRandomWalk <- function(sx, sy, sinA, cosA, d) {
    .Call('rhr_simpleRandomWalk', PACKAGE = 'rhr', sx, sy, sinA, cosA, d)
}

